### ISSUE TITLE
JVM Options doesn't work

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx_base#3]
![image](https://user-images.githubusercontent.com/17744188/86903880-9c11a780-c118-11ea-99e0-8b53aeabadba.png)
![image](https://user-images.githubusercontent.com/17744188/86904310-2fe37380-c119-11ea-9b73-58d5b53ca776.png)

Expected result:

![image](https://user-images.githubusercontent.com/17744188/86903932-af247780-c118-11ea-8ff0-c8a649a3ac21.png)

**Comment by ildipo** [comment]
This works for me now
