### ISSUE TITLE
Beakerx UI Options don't work

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx_base#4]
![image](https://user-images.githubusercontent.com/17744188/86905378-a9c82c80-c11a-11ea-85c6-db5e65a23c87.png)

**Comment by ildipo** [comment]
@EfimovVladimir can you re-test this?

**Comment by EfimovVladimir** [comment]
The current UI options works fine. But there is still deprecated option 'show catalog button'
![image](https://user-images.githubusercontent.com/17744188/91037857-68300a00-e612-11ea-9d43-48ee9810de72.png)

**Comment by ildipo** [comment]
We removed that extension so this is gone.
